/**
 *
 * $Id$
 */
package Voter.validation;

import Voter.Voter1;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Voter.Voter1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Voter1Validator {
	boolean validate();

	boolean validateLink(EList<Voter1> value);

	boolean validateVote(boolean value);
}
