<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Voter" nsURI="platform:/resource/Voter/model/Voter.ecore" nsPrefix="Voter">
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="voters" upperBound="-1"
        eType="#//Voter1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Voter1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" ordered="false" upperBound="-1"
        eType="#//Voter1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
